<?php
/**
 * RecipientStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Maileva\Client\Model;
use \Maileva\Client\ObjectSerializer;

/**
 * RecipientStatus Class Doc Comment
 *
 * @category Class
 * @description Statut du destinataire. &lt;table&gt;  &lt;tr&gt;     &lt;td&gt;DRAFT&lt;/td&gt;     &lt;td&gt;le destinataire a été ajouté à l&#x27;envoi qui est au statut draft&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;PENDING&lt;/td&gt;     &lt;td&gt;le destinataire a été ni traité, ni rejeté&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;PROCESSED&lt;/td&gt;     &lt;td&gt;le destinataire a été mis sous pli (liasse appairée si recommandée)&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;REJECTED&lt;/td&gt;     &lt;td&gt;le destinataire n&#x27;est pas valide&lt;/td&gt;   &lt;/tr&gt; &lt;/table&gt;
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RecipientStatus
{
    /**
     * Possible values of this enum
     */
    const DRAFT = 'DRAFT';
const PENDING = 'PENDING';
const PROCESSED = 'PROCESSED';
const REJECTED = 'REJECTED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DRAFT,
self::PENDING,
self::PROCESSED,
self::REJECTED,        ];
    }
}
