<?php
/**
 * DeliveryStatusesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Maileva\Client;

/**
 * DeliveryStatusesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Liste des statuts de distribution
 * @package     Maileva\Client
 * @author      Maileva Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeliveryStatusesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DeliveryStatusesResponse"
     */
    public function testDeliveryStatusesResponse()
    {
    }

    /**
     * Test attribute "delivery_statuses"
     */
    public function testPropertyDeliveryStatuses()
    {
    }

    /**
     * Test attribute "paging"
     */
    public function testPropertyPaging()
    {
    }
}
