<?php
/**
 * RecipientResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Maileva\Client;

/**
 * RecipientResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Les destinataires importés pour l&#x27;envoi
 * @package     Maileva\Client
 * @author      Maileva Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecipientResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RecipientResponse"
     */
    public function testRecipientResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "custom_id"
     */
    public function testPropertyCustomId()
    {
    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {
    }

    /**
     * Test attribute "address_line_1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "address_line_2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "address_line_3"
     */
    public function testPropertyAddressLine3()
    {
    }

    /**
     * Test attribute "address_line_4"
     */
    public function testPropertyAddressLine4()
    {
    }

    /**
     * Test attribute "address_line_5"
     */
    public function testPropertyAddressLine5()
    {
    }

    /**
     * Test attribute "address_line_6"
     */
    public function testPropertyAddressLine6()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "pages_range"
     */
    public function testPropertyPagesRange()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "status_detail"
     */
    public function testPropertyStatusDetail()
    {
    }

    /**
     * Test attribute "last_delivery_status"
     */
    public function testPropertyLastDeliveryStatus()
    {
    }

    /**
     * Test attribute "last_delivery_status_date"
     */
    public function testPropertyLastDeliveryStatusDate()
    {
    }

    /**
     * Test attribute "postage_price"
     */
    public function testPropertyPostagePrice()
    {
    }

    /**
     * Test attribute "registered_number"
     */
    public function testPropertyRegisteredNumber()
    {
    }

    /**
     * Test attribute "archive_date"
     */
    public function testPropertyArchiveDate()
    {
    }

    /**
     * Test attribute "archive_url"
     */
    public function testPropertyArchiveUrl()
    {
    }

    /**
     * Test attribute "acknowledgement_of_receipt_archive_date"
     */
    public function testPropertyAcknowledgementOfReceiptArchiveDate()
    {
    }

    /**
     * Test attribute "acknowledgement_of_receipt_url"
     */
    public function testPropertyAcknowledgementOfReceiptUrl()
    {
    }
}
