<?php
/**
 * SendingResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Maileva\Client;

/**
 * SendingResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Un envoi de LREL
 * @package     Maileva\Client
 * @author      Maileva Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SendingResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SendingResponse"
     */
    public function testSendingResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "custom_id"
     */
    public function testPropertyCustomId()
    {
    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "status_detail"
     */
    public function testPropertyStatusDetail()
    {
    }

    /**
     * Test attribute "acknowledgement_of_receipt"
     */
    public function testPropertyAcknowledgementOfReceipt()
    {
    }

    /**
     * Test attribute "acknowledgement_of_receipt_scanning"
     */
    public function testPropertyAcknowledgementOfReceiptScanning()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "submission_date"
     */
    public function testPropertySubmissionDate()
    {
    }

    /**
     * Test attribute "scheduled_date"
     */
    public function testPropertyScheduledDate()
    {
    }

    /**
     * Test attribute "processed_date"
     */
    public function testPropertyProcessedDate()
    {
    }

    /**
     * Test attribute "archive_date"
     */
    public function testPropertyArchiveDate()
    {
    }

    /**
     * Test attribute "documents_count"
     */
    public function testPropertyDocumentsCount()
    {
    }

    /**
     * Test attribute "documents_weight"
     */
    public function testPropertyDocumentsWeight()
    {
    }

    /**
     * Test attribute "pages_count"
     */
    public function testPropertyPagesCount()
    {
    }

    /**
     * Test attribute "billed_pages_count"
     */
    public function testPropertyBilledPagesCount()
    {
    }

    /**
     * Test attribute "sheets_count"
     */
    public function testPropertySheetsCount()
    {
    }

    /**
     * Test attribute "recipients_counts"
     */
    public function testPropertyRecipientsCounts()
    {
    }

    /**
     * Test attribute "color_printing"
     */
    public function testPropertyColorPrinting()
    {
    }

    /**
     * Test attribute "duplex_printing"
     */
    public function testPropertyDuplexPrinting()
    {
    }

    /**
     * Test attribute "optional_address_sheet"
     */
    public function testPropertyOptionalAddressSheet()
    {
    }

    /**
     * Test attribute "system_address_sheet"
     */
    public function testPropertySystemAddressSheet()
    {
    }

    /**
     * Test attribute "notification_email"
     */
    public function testPropertyNotificationEmail()
    {
    }

    /**
     * Test attribute "envelope_type"
     */
    public function testPropertyEnvelopeType()
    {
    }

    /**
     * Test attribute "sender_address_line_1"
     */
    public function testPropertySenderAddressLine1()
    {
    }

    /**
     * Test attribute "sender_address_line_2"
     */
    public function testPropertySenderAddressLine2()
    {
    }

    /**
     * Test attribute "sender_address_line_3"
     */
    public function testPropertySenderAddressLine3()
    {
    }

    /**
     * Test attribute "sender_address_line_4"
     */
    public function testPropertySenderAddressLine4()
    {
    }

    /**
     * Test attribute "sender_address_line_5"
     */
    public function testPropertySenderAddressLine5()
    {
    }

    /**
     * Test attribute "sender_address_line_6"
     */
    public function testPropertySenderAddressLine6()
    {
    }

    /**
     * Test attribute "sender_country_code"
     */
    public function testPropertySenderCountryCode()
    {
    }

    /**
     * Test attribute "archiving_duration"
     */
    public function testPropertyArchivingDuration()
    {
    }

    /**
     * Test attribute "return_envelope_reference"
     */
    public function testPropertyReturnEnvelopeReference()
    {
    }

    /**
     * Test attribute "deposit_proof_date"
     */
    public function testPropertyDepositProofDate()
    {
    }

    /**
     * Test attribute "deposit_proof_url"
     */
    public function testPropertyDepositProofUrl()
    {
    }
}
