<?php
/**
 * SendingStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Maileva\Client;

/**
 * SendingStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Statut d&#x27;un envoi : &lt;table border&#x3D;1&gt;  &lt;tr&gt;     &lt;td&gt;DRAFT&lt;/td&gt;     &lt;td&gt;L&#x27;envoi est au statut de brouillon, non validé par l’utilisateur&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;PENDING&lt;/td&gt;     &lt;td&gt;Le client a fait un envoi, mais il n’a pas encore été analysé par le système ou l&#x27;envoi a été reçu mais il n’a pas encore été analysé&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;ACCEPTED&lt;/td&gt;     &lt;td&gt;L&#x27;envoi a été accepté et il sera traité&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;REJECTED&lt;/td&gt;     &lt;td&gt;L&#x27;envoi est refusé&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;PROCESSED&lt;/td&gt;     &lt;td&gt;L&#x27;envoi a été traité et tous les destinataires étaient valides&lt;/td&gt;   &lt;/tr&gt;   &lt;tr&gt;     &lt;td&gt;PROCESSED_WITH_ERRORS&lt;/td&gt;     &lt;td&gt;L&#x27;envoi a été traité mais certains destinataires n’étaient pas valides&lt;/td&gt;   &lt;/tr&gt; &lt;/table&gt;
 * @package     Maileva\Client
 * @author      Maileva Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SendingStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SendingStatus"
     */
    public function testSendingStatus()
    {
    }
}
