<?php
/**
 * SendingCreationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Maileva\Client;

/**
 * SendingCreationTest Class Doc Comment
 *
 * @category    Class
 * @description un envoi
 * @package     Maileva\Client
 * @author      Maileva Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SendingCreationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SendingCreation"
     */
    public function testSendingCreation()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "custom_id"
     */
    public function testPropertyCustomId()
    {
    }

    /**
     * Test attribute "custom_data"
     */
    public function testPropertyCustomData()
    {
    }

    /**
     * Test attribute "acknowledgement_of_receipt"
     */
    public function testPropertyAcknowledgementOfReceipt()
    {
    }

    /**
     * Test attribute "acknowledgement_of_receipt_scanning"
     */
    public function testPropertyAcknowledgementOfReceiptScanning()
    {
    }

    /**
     * Test attribute "color_printing"
     */
    public function testPropertyColorPrinting()
    {
    }

    /**
     * Test attribute "duplex_printing"
     */
    public function testPropertyDuplexPrinting()
    {
    }

    /**
     * Test attribute "optional_address_sheet"
     */
    public function testPropertyOptionalAddressSheet()
    {
    }

    /**
     * Test attribute "notification_email"
     */
    public function testPropertyNotificationEmail()
    {
    }

    /**
     * Test attribute "sender_address_line_1"
     */
    public function testPropertySenderAddressLine1()
    {
    }

    /**
     * Test attribute "sender_address_line_2"
     */
    public function testPropertySenderAddressLine2()
    {
    }

    /**
     * Test attribute "sender_address_line_3"
     */
    public function testPropertySenderAddressLine3()
    {
    }

    /**
     * Test attribute "sender_address_line_4"
     */
    public function testPropertySenderAddressLine4()
    {
    }

    /**
     * Test attribute "sender_address_line_5"
     */
    public function testPropertySenderAddressLine5()
    {
    }

    /**
     * Test attribute "sender_address_line_6"
     */
    public function testPropertySenderAddressLine6()
    {
    }

    /**
     * Test attribute "sender_country_code"
     */
    public function testPropertySenderCountryCode()
    {
    }

    /**
     * Test attribute "archiving_duration"
     */
    public function testPropertyArchivingDuration()
    {
    }

    /**
     * Test attribute "return_envelope_reference"
     */
    public function testPropertyReturnEnvelopeReference()
    {
    }
}
