<?php
/**
 * DestinatairesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Maileva\Client;

use Maileva\Client\Configuration;
use Maileva\Client\ApiException;
use Maileva\Client\ObjectSerializer;

/**
 * DestinatairesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DestinatairesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for patchRecipient
     *
     * Modification partielle d'un destinataire.
     *
     */
    public function testPatchRecipient()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsDelete
     *
     * Suppression de tous les destinataires.
     *
     */
    public function testSendingsSendingIdRecipientsDelete()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsGet
     *
     * Liste des destinataires d'un envoi.
     *
     */
    public function testSendingsSendingIdRecipientsGet()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsImportsPost
     *
     * Ajout d'un ou de plusieurs destinataire(s) à l'envoi.
     *
     */
    public function testSendingsSendingIdRecipientsImportsPost()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsPost
     *
     * Ajout d'un destinataire à l'envoi.
     *
     */
    public function testSendingsSendingIdRecipientsPost()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsRecipientIdDelete
     *
     * Suprression d'un destinataire.
     *
     */
    public function testSendingsSendingIdRecipientsRecipientIdDelete()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsRecipientIdDeliveryStatusesGet
     *
     * Liste des statuts de distribution d'un destinataire.
     *
     */
    public function testSendingsSendingIdRecipientsRecipientIdDeliveryStatusesGet()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsRecipientIdDownloadAcknowledgementOfReceiptGet
     *
     * Télécharger l'avis de réception archivé du destinataire.
     *
     */
    public function testSendingsSendingIdRecipientsRecipientIdDownloadAcknowledgementOfReceiptGet()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsRecipientIdDownloadArchiveGet
     *
     * Télécharger le courrier envoyé au destinataire.
     *
     */
    public function testSendingsSendingIdRecipientsRecipientIdDownloadArchiveGet()
    {
    }

    /**
     * Test case for sendingsSendingIdRecipientsRecipientIdGet
     *
     * Détail d'un destinataire.
     *
     */
    public function testSendingsSendingIdRecipientsRecipientIdGet()
    {
    }
}
