<?php
/**
 * EnvoiApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maileva / Envoi et Suivi de Lettres Recommandées En Ligne distribuées par le facteur
 *
 * API pour envoyer et suivre des Lettres Recommandées En Ligne distribuées par le facteur  Elles comprennent les fonctions clés pour :   - créer un envoi,  - ajouter des documents et des destinataires,  - choisir ses options (noir & blanc ou couleur, recto ou recto-verso, avec ou sans AR …).  - suivre la production (date de planification, suivi de l’envoi…).  Voir la documentation \"notification_center\".
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Maileva Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Maileva\Client;

use Maileva\Client\Configuration;
use Maileva\Client\ApiException;
use Maileva\Client\ObjectSerializer;

/**
 * EnvoiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Maileva\Client
 * @author   Maileva Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EnvoiApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for sendingsGet
     *
     * Liste des envois.
     *
     */
    public function testSendingsGet()
    {
    }

    /**
     * Test case for sendingsPost
     *
     * Création d'un envoi.
     *
     */
    public function testSendingsPost()
    {
    }

    /**
     * Test case for sendingsSendingIdDelete
     *
     * Suppression d'un envoi.
     *
     */
    public function testSendingsSendingIdDelete()
    {
    }

    /**
     * Test case for sendingsSendingIdDownloadDepositProofGet
     *
     * .
     *
     */
    public function testSendingsSendingIdDownloadDepositProofGet()
    {
    }

    /**
     * Test case for sendingsSendingIdGet
     *
     * Détail d'un envoi.
     *
     */
    public function testSendingsSendingIdGet()
    {
    }

    /**
     * Test case for sendingsSendingIdPatch
     *
     * Modification des options d'envoi.
     *
     */
    public function testSendingsSendingIdPatch()
    {
    }

    /**
     * Test case for sendingsSendingIdSubmitPost
     *
     * Finalisation d'un envoi.
     *
     */
    public function testSendingsSendingIdSubmitPost()
    {
    }
}
